name: Update Filters
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  "0 0 */5 * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Run update-filters.sh
        run: |
          chmod +x ruleset_converter update-filters.sh
          ./update-filters.sh

      - name: Generate date
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Commit filters
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'filters.dat'
          default_author: user_info
          message: 'Update filters: ${{ env.DATE }}'
          push: true
